[project]
name = "workflow-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.10.1",
]

[project.scripts]
workflow-mcp = "main:main"